name: Cross repository integration test

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

concurrency:
  group: preview-pages-test-cross-repo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cross-repo-integration-test:
    if: >
      github.event_name == 'push'
      || github.event.pull_request.head.repo.full_name == github.repository && contains(github.event.pull_request.labels.*.name, 'integration-test')
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Do some kind of build
        run: mkdir test && mv README.md test/index.md

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a #2.1.0
        with:
          app_id: ${{ secrets.RAJYAN_BOT_APP_ID }}
          private_key: ${{ secrets.RAJYAN_BOT_PRIVATE_KEY }}

      - name: Preview Pages
        uses: ./
        with:
          token: ${{ steps.generate-token.outputs.token }}
          source-dir: test
          target-repository: rajyan/coverage-report
          target-dir: docs/preview-pages
          configured-dir: docs
          pr-comment: append
