
name: Cross repository integration test

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: preview-pages-test-cross-repo-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: Run

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do some kind of build
        run: mkdir test && mv README.md test/index.md

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 #1.8.0
        with:
          app_id: ${{ secrets.RAJYAN_BOT_APP_ID }}
          private_key: ${{ secrets.RAJYAN_BOT_PRIVATE_KEY }}

      - name: Preview Pages
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        uses: rajyan/preview-pages@main
        with:
          token: ${{ steps.generate-token.outputs.token }}
          source-dir: test
          target-repository: rajyan/coverage-report
          target-branch: main
          pr-comment: append
