name: Pull request lint

on:
  pull_request_target:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      pull-requests: write
    steps:
      - uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |-
            feat
            fix
            docs
            refactor
            chore
            test
          requireScope: false
