
name: Update README

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Run

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: npalm/action-docs-action@v1.4.0
      - uses: stefanzweifel/git-auto-commit-action@v4
