
name: Update README

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Run

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: npalm/action-docs-action@v1.4.0

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.RAJYAN_BOT_APP_ID }}
          private_key: ${{ secrets.RAJYAN_BOT_PRIVATE_KEY }}

      - uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ steps.generate-token.outputs.token }}